Initial commits
filetrust/k8-traffic-generator pull request #1
Opened 2020-08-24 18:08 UTC by yardenshoham

Added the basic infrastructure for the code as well as the Dockerfile

2020-08-24 19:14 UTC, faisaladnanpeltops approved these changes

2020-08-24 20:56 UTC, dinis-cruz-gw requested changes
Hi, please see comments and as mentioned on twitter please refactor into a folder with your name

2020-08-24 20:56 UTC, dinis-cruz-gw commented on custom/Dockerfile
> +    xdg-utils
Hi, this massive list of installation doesn’t look right 

Are they all needed or is there a better base docker image to use?

2020-08-24 20:56 UTC, dinis-cruz-gw commented on custom/README.md
> +
Also add instructions to build the docker image

2020-08-24 20:56 UTC, dinis-cruz-gw commented on custom/src/index.js
> +}
Can you refactor these methods into a separate class

2020-08-24 20:56 UTC, dinis-cruz-gw commented on custom/src/index.js
> +scheduleInteractions();
Refactor into separate file that consumes the class and invokes the method

2020-08-24 20:56 UTC, dinis-cruz-gw commented on custom/src/interactions.js
> +}
Refactor into utilis class

2020-08-24 20:56 UTC, dinis-cruz-gw commented on custom/src/interactions.js
> +};
Refactor this into a class that has multiple methods like: setup_browser , open page, download_file, check_hash

2020-08-24 20:56 UTC, dinis-cruz-gw commented on custom/src/interactions.js
> +module.exports = [pdfTest];
Can you add Unit Tests?

2020-08-24 21:09 UTC, yardenshoham commented on custom/Dockerfile
> +    xdg-utils
We have to have those.

See https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

2020-08-25 16:11 UTC, DinisCruz requested changes
all files need to be moved into a folder with with developer's name 

at the moment they are on the a root folder called `custom`

2020-08-25 18:28 UTC, yardenshoham commented on custom/src/interactions.js
> +module.exports = [pdfTest];
Unit tests for what? It's already a testing code of sorts

2020-08-25 18:45 UTC, yardenshoham commented
As soon as this is merged I'll write the Kubernetes manifest files

2020-08-26 16:17 UTC, dinis-cruz-gw requested changes
Looks good, you just need to fix the merge conflict

2020-08-27 00:25 UTC, dinis-cruz-gw approved these changes

2020-08-27 00:25 UTC, dinis-cruz-gw commented on upwork-devs/yarden-shoham/chart/templates/_helpers.tpl
> +{{- end }}
can you format this better so that it is more readable?

2020-08-27 00:25 UTC, dinis-cruz-gw commented on upwork-devs/yarden-shoham/chart/templates/ingress.yaml
> +  {{- end }}
this has better formating and is easier to read :)

2020-08-27 00:25 UTC, dinis-cruz-gw commented on upwork-devs/yarden-shoham/chart/values.yaml
> +  tag: latest
for now we should be using local images and not pulling them from a registry

2020-08-27 00:25 UTC, dinis-cruz-gw commented on upwork-devs/yarden-shoham/src/pdfTest.js
> +module.exports = PdfTest;
how good are you with python?

I would like to use https://github.com/pyppeteer/pyppeteer

2020-08-27 00:25 UTC, dinis-cruz-gw commented on upwork-devs/yarden-shoham/chart/values.yaml
> +targetHost: glasswallsolutions.com
I really like how you used templates and moved config data to the yaml file

2020-08-27 00:26 UTC, merged

2020-08-27 11:48 UTC, yardenshoham commented on upwork-devs/yarden-shoham/chart/values.yaml
> +  tag: latest
Sure, as you can see `pullPolicy: IfNotPresent`, so it'll only be pulled if the image doesn't exist on the node's local cache.

2020-08-27 11:49 UTC, yardenshoham commented on upwork-devs/yarden-shoham/src/pdfTest.js
> +module.exports = PdfTest;
I can do it, would you like me to scrap it and re-implement it in python?