Using artillery.io to generate traffic
filetrust/k8-traffic-generator pull request #2
Opened 2020-08-24 18:38 UTC by faisaladnanpeltops

Hi, here is my submission to generate traffic using artillery.io

2020-08-24 19:07 UTC, yardenshoham approved these changes

2020-08-24 20:45 UTC, dinis-cruz-gw requested changes

2020-08-24 20:45 UTC, dinis-cruz-gw commented on artillery/HOWTO.md
> +```
I don’t think we need the docker hub references for now

2020-08-24 20:45 UTC, dinis-cruz-gw commented on artillery/HOWTO.md
> +```
Same here, this is not needed

2020-08-24 20:45 UTC, dinis-cruz-gw commented on artillery/load.yml
> +        url: "/company"
Cool, where is the output stored?

2020-08-24 20:45 UTC, dinis-cruz-gw commented on artillery/HOWTO.md
> +```
Can you add more info to this README about what artilary is doing

Can you also create a diagram that shows what is going on

2020-08-24 20:45 UTC, dinis-cruz-gw commented on artillery/HOWTO.md
> +```
Nice touch :) 

(The installation and setup of minikube)

2020-08-24 20:45 UTC, dinis-cruz-gw commented on artillery/Dockerfile
> +FROM node:12
As mentioned in the slack environment, please refactor these files to be under a folder with your name

2020-08-24 21:26 UTC, faisaladnanpeltops commented on artillery/HOWTO.md
> +```
I'll remove this step and keep the howto simple.

2020-08-24 21:27 UTC, faisaladnanpeltops commented on artillery/load.yml
> +        url: "/company"
The output will be stored in statsd and be visualised in graphite.

2020-08-24 21:27 UTC, faisaladnanpeltops commented on artillery/HOWTO.md
> +```
Sure thing

2020-08-24 21:28 UTC, faisaladnanpeltops commented on artillery/HOWTO.md
> +```
Thank you :)

2020-08-24 21:28 UTC, faisaladnanpeltops commented on artillery/Dockerfile
> +FROM node:12
Ok.

2020-08-25 08:29 UTC, faisaladnanpeltops reviewed
I've read the requested changes and updating them in the forked repo.

2020-08-25 16:50 UTC, DinisCruz commented on upwork-devs/faisal-adnan/artillery.yaml
> +    image: peltops/gsl_artillery:v2
can you document the command to build this image

2020-08-25 16:50 UTC, merged