Add helm chart installation instructions to README.md
filetrust/k8-traffic-generator pull request #42
Opened 2020-08-30 16:09 UTC by yardenshoham

2020-08-30 16:56 UTC, DinisCruz requested changes

2020-08-30 16:56 UTC, DinisCruz commented on upwork-devs/yarden-shoham/chart/templates/_helpers.tpl
> +{{- end }}
You lost the formatting 

Can you add it back (that code indents makes it easier to read)

2020-08-30 17:06 UTC, yardenshoham commented on upwork-devs/yarden-shoham/chart/templates/_helpers.tpl
> +{{- end }}
No, apparently it's whitespace sensitive as it's helpers for a templating engine. For example, see: https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/_helpers.tpl.

2020-08-31 23:29 UTC, DinisCruz approved these changes

2020-08-31 23:29 UTC, merged