Create MD (markdown) file that explains the workflow
filetrust/k8-traffic-generator pull request #64
Opened 2020-09-03 13:12 UTC by ggrig

2020-09-06 07:54 UTC, yardenshoham commented
Closes #11

2020-09-06 23:59 UTC, DinisCruz requested changes

2020-09-06 23:59 UTC, DinisCruz commented on docs/rebuild-engine-as-a-target.md
> +
This workflow description is spot on 👍

2020-09-06 23:59 UTC, DinisCruz commented on docs/README.md
> +
On this mode, replace URL with Action

Those actions will be specific to a target website

I like the idea to either define the Actions sequence of events , or to have it running at random

2020-09-06 23:59 UTC, DinisCruz commented on docs/README.md
> +
Please drop this mode, you are going on an ‘over-engineering’ path

We don’t this this type of modularised module

2020-09-06 23:59 UTC, DinisCruz commented on docs/README.md
> +![logging](pngs/logging-workflow.png)
Yes 👍

2020-09-07 07:24 UTC, ggrig commented on docs/README.md
> +
Hi Dinis,
Do you mean that no POD will need supporting multiple sites?
As a consequence, do you say we do not need to have plugins there?

2020-09-07 07:49 UTC, ggrig commented on docs/README.md
> +
Done

2020-09-07 14:00 UTC, ggrig commented on docs/README.md
> +
Done

2020-09-08 23:02 UTC, DinisCruz approved these changes

2020-09-08 23:02 UTC, merged