Traffic generation and file validation for gov.uk
filetrust/k8-traffic-generator pull request #88
Opened 2020-09-10 13:50 UTC by pranaysahith

2020-09-10 21:31 UTC, yardenshoham requested changes
I really like your use of environment variables for configuration!

2020-09-10 21:31 UTC, yardenshoham commented on upwork-devs/pranay-sahith/gov-uk/docker-compose.yaml
> +    image: traffic_generator
Please use `-` instead of `_`.

2020-09-10 21:31 UTC, yardenshoham commented on upwork-devs/pranay-sahith/gov-uk/gov-uk_job.yaml
> +        image: pranaysahith/traffic_generator_gov_uk:0.0.2
Please use `-` instead of `_`.

2020-09-11 09:05 UTC, yardenshoham approved these changes

2020-09-12 23:47 UTC, DinisCruz commented on upwork-devs/pranay-sahith/gov-uk/tests/test_gov_uk.py
> +            assert result == "File is clean!"
Nice :)

2020-09-12 23:47 UTC, merged